schema_version: 1

context:
  name: dbetto
  version: "1.3.2"
  python_min: "3.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/dbetto-${{ version }}.tar.gz
  sha256: 2fbbb5bda705851d3dd29f75e8aead4dbe507be893816df506ccadb3fead7c7d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - pyyaml

tests:
  - python:
      imports:
        - dbetto
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  summary: A tiny text file based database
  description: |
    dbetto is a lightweight Python library that enables seamless access and
    management of text-based databases (JSON/YAML) scattered across your
    filesystem.
    Whether you're handling nested data structures or querying data by validity
    periods, dbetto simplifies it all with an intuitive interface.
  homepage: https://github.com/gipert/dbetto
  repository: https://github.com/gipert/dbetto
  documentation: https://dbetto.readthedocs.io/

extra:
  recipe-maintainers:
    - gipert
    - matthewfeickert
